"""empty message

Revision ID: 9886ba90970a
Revises: 07483a90cc40
Create Date: 2025-02-13 16:40:32.166126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9886ba90970a'
down_revision: Union[str, None] = '07483a90cc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshot', sa.Column('is_used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshot', 'is_used')
    # ### end Alembic commands ###
