"""empty message

Revision ID: 7315c7202c3c
Revises: b55bcc764731
Create Date: 2025-02-17 16:03:31.710929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7315c7202c3c'
down_revision: Union[str, None] = 'b55bcc764731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_ibfk_1', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'screenshot', ['screenshot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_ibfk_1', 'notification', 'screenshot', ['screenshot_id'], ['id'])
    # ### end Alembic commands ###
