"""empty message

Revision ID: bb4739f8db24
Revises: 9886ba90970a
Create Date: 2025-02-14 11:37:51.269426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb4739f8db24'
down_revision: Union[str, None] = '9886ba90970a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenshot', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('screenshot', 'category_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('screenshot', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenshot', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('screenshot', 'category_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('screenshot', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
