"""empty message

Revision ID: 07483a90cc40
Revises: 7e38de6a31d5
Create Date: 2025-02-13 14:12:19.706712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07483a90cc40'
down_revision: Union[str, None] = '7e38de6a31d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'message')
    # ### end Alembic commands ###
